Repository TheRedstoneRadiant/Qurl.gq, pull requests merged in 2022-10, with the labels that each got.

#1 Connect to MongoDB
  .env.example
  index.js
  package-lock.json
Labels: hacktoberfest, hacktoberfest-approved

#2 feat: add mongodb as a dependancy
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-approved

#3 feat: Create main homepage UI
  public/css/style.css
  views/index.ejs
Labels: hacktoberfest, hacktoberfest-approved

#6 feat: add light/dark mode switcher
  public/css/style.css
  public/js/theme.js
  views/index.ejs
  views/info.ejs
Labels: hacktoberfest, hacktoberfest-accepted

#7 Router
  index.js
  router/createUrl.js
  router/index.js
  router/shortUrl.js
  views/404.ejs
Labels: hacktoberfest, hacktoberfest-accepted

#19 Feat!: User now has option to log ips or not
  CONTRIBUTORS.md
  package-lock.json
  public/js/index.js
  router/createUrl.js
  router/shortUrl.js
  views/index.ejs
  views/info.ejs
Labels: hacktoberfest-accepted

#22 Added the map
  .env.example
  public/css/footer.css
  public/css/index.css
  public/css/info.css
  public/css/style.css
  public/img/pin.png
  public/js/mapbox.js
  public/js/theme.js
  router/shortUrl.js
  views/404.ejs
  views/index.ejs
  views/info.ejs
  views/partials/footer.ejs
  views/partials/header.ejs
Labels: hacktoberfest-accepted
